# Generated by Django 5.1.5 on 2025-02-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_quarterlygoal_options_alter_yearlygoal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalyearlygoal',
            name='life_sector',
            field=models.CharField(choices=[('other', 'Other'), ('health', 'Health & Fitness'), ('career', 'Career & Work'), ('relationships', 'Relationships'), ('personal', 'Personal Growth'), ('finance', 'Finance')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='yearlygoal',
            name='life_sector',
            field=models.CharField(choices=[('other', 'Other'), ('health', 'Health & Fitness'), ('career', 'Career & Work'), ('relationships', 'Relationships'), ('personal', 'Personal Growth'), ('finance', 'Finance')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalquarterlygoal',
            name='life_sector',
            field=models.CharField(choices=[('other', 'Other'), ('health', 'Health & Fitness'), ('career', 'Career & Work'), ('relationships', 'Relationships'), ('personal', 'Personal Growth'), ('finance', 'Finance')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='quarterlygoal',
            name='life_sector',
            field=models.CharField(choices=[('other', 'Other'), ('health', 'Health & Fitness'), ('career', 'Career & Work'), ('relationships', 'Relationships'), ('personal', 'Personal Growth'), ('finance', 'Finance')], default='other', max_length=20),
        ),
    ]
