# Generated by Django 5.1.5 on 2025-02-04 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_historicalyearlygoal_life_sector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalyearlygoal',
            name='title',
        ),
        migrations.RemoveField(
            model_name='yearlygoal',
            name='title',
        ),
    ]
