# Generated by Django 5.1.5 on 2025-02-04 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_historicalyearlygoal_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpi',
            options={'ordering': ['-created_at'], 'verbose_name': 'KPI', 'verbose_name_plural': 'KPIs'},
        ),
        migrations.AlterField(
            model_name='kpi',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='quarterly_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.quarterlygoal'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='target_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='unit',
            field=models.CharField(default='units', max_length=50),
        ),
    ]
