# Generated by Django 5.1.5 on 2025-02-04 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_kpi_options_alter_kpi_frequency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='title',
        ),
    ]
