# Generated by Django 5.0.1 on 2025-02-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_kpi_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpirecord',
            options={'ordering': ['-entry_date']},
        ),
        migrations.AlterField(
            model_name='kpirecord',
            name='value',
            field=models.FloatField(),
        ),
    ]
